[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "any", "--transition-fps", "60"]
set = true

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = "kill -SIGUSR1 $(pidof kitty)"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

# [templates.pywalfox]
# input_path = '~/.config/matugen/templates/pywalfox-colors.json'
# output_path = '~/.cache/wal/colors.json'
# post_hook = 'pywalfox update'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

# [templates.cava]
# input_path = '~/.config/matugen/templates/matugen-cava'
# output_path = '~/.config/cava/config'
# post_hook = "pkill -USR1 cava"

# [templates.spicetify]
# input_path = '~/.config/matugen/templates/spotify-colors.ini'
# output_path = '~/.config/spicetify/Themes/text/color.ini'

# [templates.vesktop]
# input_path = '~/.config/matugen/templates/midnight-discord.css'
# output_path = '~/.config/vesktop/themes/matugen.css'


[templates.nvim]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-dark.lua'

[templates.nvimlight]
input_path = '~/.config/nvim/pywal/matugen.lua'
output_path = '~/.cache/wal/base46-light.lua'

[templates.pywal]
input_path = '~/.config/nvim/pywal/waltemplate'
output_path = '~/.cache/wal/colors'

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
