timeout: 0

/Arch Linux (linux)
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: root=PARTUUID=<CHANGE-ME> zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs splash quiet loglevel=3 rd.udev.log_level=3 vt.global_cursor_default=0
    module_path: boot():/initramfs-linux.img
