cursor #e6f0ff
cursor_text_color #ffffff

foreground            #e6f0ff
background            #000000
selection_foreground  #000000
selection_background  #999999
url_color             #f0f0f0

color0   #000000
color1   #ff7272
color2   #92f078
color3   #ffe372
color4   #e3e3e3
color5   #6f6f6f
color6   #f0f0f0
color7   #fcecec
color8   #9c9090
color9   #ff9f9f
color10  #b9ffa5
color11  #ffeda5
color12  #ffffff
color13  #ffffff
color14  #ffffff
color15  #fff8f8
