set -g prefix M-s
unbind C-b
bind M-s send-prefix

set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g base-index 1
set -g pane-base-index 1
set -w -g automatic-rename on

set -g status-position top
set -g status-bg default
set -g status-fg default
set -g status-left ""
set -g status-right ""
set -g status-interval 1

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Initialize TPM
run '~/.config/tmux/plugins/tpm/tpm'

bind t run-shell '
  path=$(tmux display-message -p "#{pane_current_path}")
  if [ "$(tmux list-panes | wc -l)" -eq 1 ]; then
    tmux split-window -v -l 30% -c "$path"
  else
    h=$(tmux display-message -p "#{pane_height}" -t !)
    if [ "$h" -le 2 ]; then
      tmux resize-pane -t ! -y 30
      tmux send-keys -t ! C-l "cd $(tmux display-message -p "#{pane_current_path}")" Enter
      tmux select-pane -t !
    else
      tmux resize-pane -t ! -y 1
    fi
  fi
'

source-file ~/.config/tmux/statusline.conf
