return {
  {
    "AstroNvim/astroui",
    ---@type AstroUIOpts
    opts = {
      status = {
        colors = {
          fg = "#cdd6f4",
          bg = "#000000",
          section_fg = "#cdd6f4",
          section_bg = "#000000",
          mode_fg = "#000000",
          git_branch_fg = "#cba6f7",
          treesitter_fg = "#a6e3a1",
          virtual_env_fg = "#f9e2af",
          scrollbar = "#cba6f7",
          close_fg = "#f38ba8",
          git_added = "#a6e3a1",
          git_changed = "#f9e2af",
          git_removed = "#f38ba8",
          diag_ERROR = "#f38ba8",
          diag_WARN = "#fab387",
          diag_INFO = "#89dceb",
          diag_HINT = "#cba6f7",
          winbar_fg = "#a6adc8",
          winbar_bg = "#000000",
          winbarnc_fg = "#6c7086",
          winbarnc_bg = "#000000",
          tabline_bg = "#000000",
          tabline_fg = "#000000",
          buffer_fg = "#a6adc8",
          buffer_path_fg = "#6c7086",
          buffer_close_fg = "#a6adc8",
          buffer_bg = "#000000",
          buffer_active_fg = "#cdd6f4",
          buffer_active_path_fg = "#6c7086",
          buffer_active_close_fg = "#f38ba8",
          buffer_active_bg = "#111111",
          buffer_visible_fg = "#cdd6f4",
          buffer_visible_path_fg = "#6c7086",
          buffer_visible_close_fg = "#f38ba8",
          buffer_visible_bg = "#111111",
          buffer_overflow_fg = "#6c7086",
          buffer_overflow_bg = "#000000",
          buffer_picker_fg = "#f38ba8",
          tab_close_fg = "#f38ba8",
          tab_close_bg = "#000000",
          tab_fg = "#a6adc8",
          tab_bg = "#000000",
          tab_active_fg = "#cdd6f4",
          tab_active_bg = "#111111",
          inactive = "#45475a",
          normal = "#89b4fa",
          insert = "#a6e3a1",
          visual = "#cba6f7",
          replace = "#f38ba8",
          command = "#f9e2af",
          terminal = "#a6e3a1",
        },
      },
    },
  },
}
